// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: http://localhost:7870
// Generated: 2026-06-08T01:59:49.138Z

export type Hex = `***REMOVED***${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '***REMOVED***3c3c43' | '***REMOVED***000000' | '***REMOVED***ffffff' | '***REMOVED***34c759' | '***REMOVED***787880' | '***REMOVED***ff3b30' | '***REMOVED***5856d6' | '***REMOVED***e5e5ea' | '***REMOVED***ff6b35' | '***REMOVED***af52de' | '***REMOVED***ff9500' | '***REMOVED***ff2d55' | '***REMOVED***f2f2f7' | '***REMOVED***c6c6c8';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Arial' | 'SF Mono' | 'Times New Roman';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '500' | '600';

export type SpacingToken = '1px' | '20px' | '27px' | '32px' | '48px' | '444px';

export type RadiusToken = '10px' | '13px' | '50px' | '999px';

export type DurationToken = '150ms' | '200ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
