// Framer Motion presets — generated by designlang (motionlang)
// Source: http://localhost:7870
// 2026-06-08T01:59:49.142Z
//
//   import { transitions, variants } from './localhost-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  standard: [0.25, 1, 0.5, 1],
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.15,
  sm: 0.2,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.2, ease: easings.standard },
  fast:  { duration: 0.100, ease: easings.standard },
  slow:  { duration: 0.360, ease: easings.standard },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.050 } },
  },
};

export default { easings, durations, transitions, variants };
