#!/usr/bin/env python3
"""
daily_memory_extract.py — 每日提取昨日聊天重點（v2 重寫版）
由 main GG 嘅 cron 每日 06:00 HKT 觸發

解決 v1 (bash) 問題:
- ❌ grep/sed parse JSON → ✅ Python json module
- ❌ timeout 30秒易斷 → ✅ timeout 60秒 + retry
- ❌ 2>/dev/null 食 error → ✅ 完整 error handling + logging
- ❌ Summary generation 停頓 → ✅ 原子寫入 + 分段處理

用途:
1. 從 GG-Work VM query 工作重點
2. 從 GG-Person VM query 個人重點
3. 整合成一日摘要，寫入 memory/YYYY-MM-DD_summary.md
4. 確保 main GG 唔會「間歇性失憶」
"""
import json, os, subprocess, sys, time
from datetime import datetime, timedelta
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
from gg_event_logger_v2 import get_logger

WORKSPACE = os.path.expanduser("~/.openclaw/workspace")
SCRIPT_DIR = os.path.join(WORKSPACE, "scripts/vm")
MEMORY_DIR = os.path.join(WORKSPACE, "memory")
LOG_FILE = f"/tmp/daily_memory_extract.log"

def log(msg):
    """Log with timestamp"""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] {msg}"
    print(line)
    with open(LOG_FILE, "a") as f:
        f.write(line + "\n")

def query_vm(target, prompt, timeout=60):
    """Query a VM and return the content string"""
    vm_query = os.path.join(SCRIPT_DIR, "vm_query.py")
    try:
        result = subprocess.run(
            [sys.executable, vm_query, target, prompt],
            capture_output=True, text=True, timeout=timeout
        )
        if result.returncode != 0:
            log(f"  ⚠️ vm_query.py returned {result.returncode}: {result.stderr[:200]}")
            return None
        
        data = json.loads(result.stdout)
        if data.get("ok"):
            content = data.get("content", "")
            return content.strip() if content else None
        else:
            log(f"  ⚠️ VM query failed: {data.get('error', 'unknown')}")
            return None
    except subprocess.TimeoutExpired:
        log(f"  ⚠️ VM query timeout after {timeout}s")
        return None
    except json.JSONDecodeError as e:
        log(f"  ⚠️ JSON parse error: {e}")
        log(f"     Raw output snippet: {result.stdout[:200] if 'result' in dir() else 'N/A'}")
        return None
    except Exception as e:
        log(f"  ⚠️ Unexpected error: {e}")
        return None

def get_target_date_str():
    """Get yesterday's date as YYYY-MM-DD"""
    yesterday = datetime.now() - timedelta(days=1)
    return yesterday.strftime("%Y-%m-%d")

def main():
    log("=" * 50)
    log("📥 Daily Memory Extract — Starting")
    
    yesterday = get_target_date_str()
    today = datetime.now().strftime("%Y-%m-%d")
    get_logger().record('memory', f'Daily memory extract for {yesterday}', source='cron')
    summary_file = os.path.join(MEMORY_DIR, f"{today}_summary.md")
    
    log(f"Target date: {yesterday}")
    log(f"Summary file: {summary_file}")
    
    # Step 1: Query GG-Work
    log("Step 1/3: Querying GG-Work VM...")
    work_summary = query_vm(
        "work",
        f"List ONLY the key work facts from {yesterday} that GG main should remember about Terrence. "
        f"Format: bullet points, max 5 items. Pure facts, no commentary.",
        timeout=60
    )
    work_summary_str = work_summary if work_summary else ''
    work_len = len(work_summary_str)
    if work_summary:
        log(f"  ✅ Got work summary ({work_len} chars)")
    else:
        log("  ⚠️ No work summary available")
        work_summary = "_No work records found_"
    
    # Step 2: Query GG-Person
    log("Step 2/3: Querying GG-Person VM...")
    person_summary = query_vm(
        "person",
        f"List ONLY the key personal facts from {yesterday} about Terrence that GG main should remember. "
        f"Format: bullet points, max 5 items. Pure facts, no commentary.",
        timeout=60
    )
    person_summary_str = person_summary if person_summary else ''
    person_len = len(person_summary_str)
    if person_summary:
        log(f"  ✅ Got person summary ({person_len} chars)")
    else:
        log("  ⚠️ No person summary available")
        person_summary = "_No personal records found_"
    
    # Step 3: Generate summary file (atomic write)
    log("Step 3/3: Generating summary file...")
    
    # Sanitize content: remove any JSON artifacts or escape sequences
    for var_name in ["work_summary", "person_summary"]:
        var = locals()[var_name]
        if var and var.startswith('"') and var.endswith('"'):
            locals()[var_name] = var[1:-1]
    
    summary_content = f"""# 🧠 Daily Memory Digest — {yesterday}

> Generated: {today} 06:00 HKT
> Source: Main GG + GG-Work + GG-Person

## 💼 Work Highlights
{work_summary}

## 🏠 Personal Highlights
{person_summary}

## 🔄 System State
- Main GG: active
- GG-Work: active
- GG-Person: active
- Memory maintenance crons: daily extract (06:00) + nightly consolidation (23:55)

---
*Auto-generated by daily_memory_extract.py*
"""
    
    # Write to temp file first, then atomic rename
    tmp_file = summary_file + ".tmp"
    try:
        os.makedirs(os.path.dirname(summary_file), exist_ok=True)
        with open(tmp_file, "w") as f:
            f.write(summary_content)
        os.rename(tmp_file, summary_file)
        log(f"  ✅ Summary written ({len(summary_content)} bytes)")
    except Exception as e:
        log(f"  ❌ Failed to write summary: {e}")
        return False
    
    log(f"✅ Daily Memory Extract complete — work: {work_len} chars, personal: {person_len} chars")
    get_logger().record('memory', f'Daily memory extract complete — work: {work_len} chars, personal: {person_len} chars', source='cron')
    return True

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
