apiVersion: v1
kind: Namespace
metadata:
  name: kong-cp-uat
  labels:
    app.kubernetes.io/part-of: fubon-kong-poc
    fubon.com.hk/environment: kong-poc-uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong-dp-uat
  labels:
    app.kubernetes.io/part-of: fubon-kong-poc
    fubon.com.hk/environment: kong-poc-uat
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-sa
  namespace: kong-cp-uat
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-sa
  namespace: kong-dp-uat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-release-manager
  namespace: kong-cp-uat
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "events", "pods", "pods/log", "secrets", "serviceaccounts", "services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-sa-release-manager
  namespace: kong-cp-uat
subjects:
  - kind: ServiceAccount
    name: kong-sa
    namespace: kong-cp-uat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-release-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-release-manager
  namespace: kong-dp-uat
rules:
  - apiGroups: [""]
    resources: ["configmaps", "endpoints", "events", "pods", "pods/log", "secrets", "serviceaccounts", "services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-sa-release-manager
  namespace: kong-dp-uat
subjects:
  - kind: ServiceAccount
    name: kong-sa
    namespace: kong-dp-uat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-release-manager
